### ISSUE TITLE
docker-compose for self hosting ?

### ISSUE THREAD

**Issue by rgarrigue** [dest4/buffer-player#1]
Hello

I just discovered adblockradio, it's a great project ! 

After trying the web demo, I was exploring how to host it on my server via docker (like all my other stuff). I see a Dockerfile here, but examining it I'm wondering where's the machine learning part ? I guess you need something like TensorFlow loaded with your current knowledge base ?

I'm aiming at a docker-compose to get it running. Maybe you already have one ? 

Best regards,

**Comment by dest4** [comment]
Hello,
the dockerfile in the repo is obsolete. Sorry for the confusion.
The official instructions to get the player running are here https://github.com/adblockradio/buffer-player#from-source

(If you are fluent with Docker, help would be appreciated to update it)

**Comment by dest4** [comment]
Update on that topic:
The machine learning part is located in a dependency of this project. That dependency is the main inference algorithm and its source is available here: https://github.com/adblockradio/adblockradio

I updated the Docker stuff. `docker-build.sh` creates a Docker image for you. `docker-run.sh` is an example of how you can run it.
I pushed an image on Docker hub: https://hub.docker.com/r/adblockradio/buffer, feel free to pull it.
