### ISSUE TITLE
Still building?

### ISSUE THREAD

**Issue by machineloop** [dest4/buffer-player#3]
Thanks for open sourcing, I'm having trouble building on the recommended node version 10.9.0 and npm version 6.4.1... I've followed the README.md instructions on MacOS, but get stuck on the last step. Does the project still build, I'd like to try to help with UI, building MacOS and Windows binaries, maybe try a basic React Native version...

Thanks again for your work on this! Really curious to play with the UI surfacing the ML ad detection, thanks!

**Comment by dest4** [comment]
Hi! Thanks for your interest in giving a help!
Could you please share the error messages you encounter?
It may not build anymore, I haven't tested very recently on Linux, and have never tested on a Mac.

A few days ago I have created a forum to have more dynamic and open exchanges, outside of Github issues. If you are okay with this, please drop me an empty email at contact@adblockradio.com and I will send you an invite in return.
