### ISSUE TITLE
RTL2 is not showing properly

### ISSUE THREAD

**Issue by Harfeur** [dest4/buffer-player#4]
When using browser AdBlock Radio, the station RTL2 is showing data (see screenshot)
![image](https://user-images.githubusercontent.com/22135449/65822773-556a5500-e24a-11e9-9ebf-14e4e5ad4b14.png)

**Comment by dest4** [comment]
Sorry for the very late answer. This was caused by a bug in https://github.com/adblockradio/webradio-metadata (which is now unmaintained)
